# Generated by Django 4.2.5 on 2023-11-03 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusActive', models.CharField(max_length=225)),
                ('EquipmentName', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeName', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('FullName', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleuser', to='Entity.role')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrole', to='Entity.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorIP', models.CharField(max_length=225)),
                ('SensorName', models.CharField(max_length=225)),
                ('StatusSensor', models.CharField(max_length=225)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='Entity.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeName', models.CharField(max_length=225)),
                ('Home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Entity.home')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='Entity.user'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='Entity.room'),
        ),
    ]
