# Generated by Django 4.2.7 on 2023-11-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusActive', models.CharField(max_length=225)),
                ('EquipmentName', models.CharField(max_length=225)),
                ('EquipmentKey', models.CharField(max_length=225)),
                ('EquipmentType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentAdminName', models.CharField(max_length=225, unique=True)),
                ('EquipmentAdminType', models.IntegerField()),
                ('EquipmentAdminKey', models.CharField(max_length=225, unique=True)),
                ('EquipmentAdminStatus', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeName', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomAdminName', models.CharField(max_length=225, unique=True)),
                ('RoomAdminKey', models.CharField(max_length=225, unique=True)),
                ('RoomAdminStatus', models.CharField(max_length=225)),
                ('RoomAdminImg', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('FullName', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleuser', to='Entity.role')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrole', to='Entity.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorIP', models.CharField(max_length=225)),
                ('SensorName', models.CharField(max_length=225)),
                ('StatusSensor', models.CharField(max_length=225)),
                ('Equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='Entity.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=225)),
                ('Home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Entity.home')),
                ('RoomAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Entity.roomadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusMode', models.CharField(max_length=225)),
                ('Home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='Entity.home')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='Entity.user'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusActive', models.CharField(max_length=225)),
                ('Temprature', models.FloatField(blank=True, null=True)),
                ('Humidity', models.FloatField(blank=True, null=True)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='Entity.equipment')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.user')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='EquipmentAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='Entity.equipmentadmin'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='Entity.room'),
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusActive', models.CharField(max_length=225)),
                ('TimeAction', models.DateTimeField()),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clocks', to='Entity.equipment')),
            ],
        ),
    ]
