# Generated by Django 4.2.7 on 2023-12-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='StatusRoom',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
    ]
