# Generated by Django 4.2.7 on 2023-11-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0002_alter_sensor_equipment_clock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='HomeName',
            new_name='RoomName',
        ),
        migrations.AddField(
            model_name='equipment',
            name='EquipmentType',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusActive', models.CharField(max_length=225)),
                ('Temprature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='Entity.equipment')),
            ],
        ),
    ]
