# Generated by Django 4.2.7 on 2023-11-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_rename_homename_room_roomname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='EquipmentType',
            field=models.IntegerField(),
        ),
    ]
