# Generated by Django 4.2.7 on 2023-11-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0005_history_user_alter_history_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Entity.user'),
        ),
    ]
