# Generated by Django 4.2.7 on 2023-11-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0006_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.user'),
        ),
    ]
