# Generated by Django 4.2.7 on 2023-11-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0007_alter_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='EquipmentKey',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
