# Generated by Django 4.2.7 on 2023-11-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0008_equipment_equipmentkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentAdminName', models.CharField(max_length=225, unique=True)),
                ('EquipmentAdminType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomAdminName', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='EquipmentAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipmentAdmin', to='Entity.equipmentadmin'),
        ),
        migrations.AddField(
            model_name='room',
            name='RoomAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomAdmin', to='Entity.roomadmin'),
        ),
    ]
