# Generated by Django 4.2.7 on 2023-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0009_equipmentadmin_roomadmin_equipment_equipmentadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentadmin',
            name='EquipmentAdminKey',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roomadmin',
            name='RoomAdminKey',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
    ]
