# Generated by Django 4.2.7 on 2023-11-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0011_equipmentadmin_equipmentadminstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='EquipmentAdmin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipmentAdmin', to='Entity.equipmentadmin'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='EquipmentKey',
            field=models.CharField(default='d', max_length=225),
        ),
        migrations.AlterField(
            model_name='equipmentadmin',
            name='EquipmentAdminKey',
            field=models.CharField(default='d', max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentadmin',
            name='EquipmentAdminStatus',
            field=models.CharField(default='2', max_length=225),
        ),
        migrations.AlterField(
            model_name='room',
            name='RoomAdmin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roomAdmin', to='Entity.roomadmin'),
        ),
        migrations.AlterField(
            model_name='roomadmin',
            name='RoomAdminKey',
            field=models.CharField(default='1', max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='roomadmin',
            name='RoomAdminStatus',
            field=models.CharField(default='1', max_length=225),
        ),
    ]
