# Generated by Django 4.2.7 on 2023-11-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0013_alter_roomadmin_roomadminkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='EquipmentAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipmentAdmin', to='Entity.equipmentadmin'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='EquipmentKey',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='equipmentadmin',
            name='EquipmentAdminKey',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentadmin',
            name='EquipmentAdminStatus',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='room',
            name='RoomAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomAdmin', to='Entity.roomadmin'),
        ),
    ]
