# Generated by Django 4.2.7 on 2023-11-29 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0014_alter_equipment_equipmentadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusMode', models.CharField(max_length=225)),
                ('Home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.home')),
            ],
        ),
    ]
